using namespace System.Collections.Generic
write-warning 'is not set to auto load, yet'
function Dotils.New.UsingStatement {
    [OutputType([string])]
    param(
        [Alias('TemplateName', 'Name', 'Kind')]
        [ArgumentCompletions(
            'All', 'Default', 'Linq', 'Generic', 'Automation', 'Misc', 'Culture', 'Microsoft'
        )]
        [string[]]$GroupName = 'Default',
        # return namespace only, without keywords
        [switch]$PassThru
    )
    $Names = [ordered]@{}
    $Names.Default = @(
        'System.Collections.Generic'
        'System.Globalization'
        'Linq'
        'Linq.Expressions'
        'Linq.Expressions.Interpreter'
        'System.Collections'
        'System.Collections.Generic'
        'System.Management.Automation'
        'System.Management.Automation.Language'
        'Xml.Linq'
    )

    $Names.Linq = @(
        'Linq'
        'Linq.Expressions'
        'Linq.Expressions.Interpreter'
        'Xml.Linq'
    )
    $Names.Generic = @(
        'System.Collections'
        'System.Collections.Generic'
    )
    $Names.Automation = @(
        'System.Management.Automation'
        'System.Management.Automation.Language'
    )
    $Names.Culture = @(
        'Globalization'
    )
    $Names.Misc = @(
        'Microsoft.CodeAnalysis.Text'
        'Microsoft.PowerShell.Commands'
        'Microsoft.PowerShell.Commands'
        'System.Collections.Generic'
        'System.Collections.Immutable'
        'System.Collections'
        'System.Configuration.Assemblies'
        'System.Management.Automation.Language'
        'System.Management.Automation'
        'System.Reflection'
        'System.Security.Authentication'
        'System.Security.Cryptography.X509Certificates'
        'System.Security.Cryptography'
        'System.Security.Policy'

        'PoshCode.Pansies.ColorSpaces.Comparisons'
        'PoshCode.Pansies.ColorSpaces.Conversions'
        'PoshCode.Pansies.ColorSpaces'
        'PoshCode.Pansies.Commands'
        'PoshCode.Pansies.Palettes'
        'PoshCode.Pansies.Provider'
        'PoshCode.Pansies'

        'Collections.Concurrent'
        'Collections.Generic'
        'Collections.Immutable'
        'Collections.ObjectModel'
        'Collections.Specialized'
        'Collections'

        'ComponentModel.Design.Serialization'
        'ComponentModel.Design'
        'ComponentModel'
        'Configuration.Assemblies'
        'Configuration'
        'Data.Common'
        'Data.Odbc'
        'Data.OleDb'
        'Data.OracleClient'
        'Data.Sql'
        'Data.SqlClient'
        'Data.SqlTypes'
        'Data'
        'Diagnostics.CodeAnalysis'
        'Diagnostics.Contracts'
        'Diagnostics.Eventing.Reader'
        'Diagnostics.Eventing'
        'Diagnostics.Metrics'
        'Diagnostics.SymbolStore'
        'Diagnostics.Tracing'
        'Diagnostics'

        'IO.Compression'
        'IO.Enumeration'
        'IO.MemoryMappedFiles'
        'IO.Packaging'
        'IO.Pipelines'
        'IO.Pipes'
        'IO'

        'Management.Automation.Configuration'
        'Management.Automation.Host'
        'Management.Automation.Internal'
        'Management.Automation.Language'
        'Management.Automation.Provider'
        'Management.Automation.PSTasks'
        'Management.Automation.Remoting.Client'
        'Management.Automation.Remoting.Internal'
        'Management.Automation.Remoting.WSMan'
        'Management.Automation.Remoting'
        'Management.Automation.Runspaces'
        'Management.Automation.Security'
        'Management.Automation.Subsystem.DSC'
        'Management.Automation.Subsystem.Prediction'
        'Management.Automation.Subsystem'
        'Management.Automation.Tracing'
        'Management.Automation'
        'Management'

        'Net'
        'Net.Cache'
        'Net.Http'
        'Net.Http.Headers'
        'Net.Mail'
        'Net.Mime'
        'Net.NetworkInformation'
        'Net.PeerToPeer'
        'Net.PeerToPeer.Collaboration'
        'Net.Quic'
        'Net.Security'
        'Net.Sockets'
        'Net.WebSockets'
        'Numerics'

        'Numerics'
        'Reactive'
        'Reactive.Concurrency'
        'Reactive.Disposables'
        'Reactive.Joins'
        'Reactive.Linq'
        'Reactive.PlatformServices'
        'Reactive.Subjects'
        'Reactive.Threading.Tasks'
        'Reflection'
        'Reflection.Emit'
        'Reflection.Metadata'
        'Reflection.Metadata.Ecma335'
        'Reflection.PortableExecutable'

        # 'Resources'

        'Runtime'
        'Runtime.CompilerServices'
        'Runtime.ConstrainedExecution'
        'Runtime.ExceptionServices'
        'Runtime.InteropServices'
        'Runtime.InteropServices.ComTypes'
        'Runtime.InteropServices.Marshalling'
        'Runtime.InteropServices.ObjectiveC'
        'Runtime.Intrinsics'
        'Runtime.Intrinsics.Arm'
        'Runtime.Intrinsics.X86'
        'Runtime.Loader'
        'Runtime.Remoting'
        'Runtime.Serialization'
        'Runtime.Serialization.Formatters'
        'Runtime.Serialization.Formatters.Binary'
        'Runtime.Versioning'

        'Security'
        'Security.AccessControl'
        'Security.Authentication'
        'Security.Authentication.ExtendedProtection'
        'Security.Claims'
        'Security.Cryptography'
        'Security.Cryptography.Pkcs'
        'Security.Cryptography.X509Certificates'
        'Security.Cryptography.Xml'
        'Security.Permissions'
        'Security.Policy'
        'Security.Principal'
        'ServiceProcess'

        'Text'
        'Text.RegularExpressions'
        'Text.Unicode'

        'Threading'
        'Threading.Channels'
        'Threading.Tasks'
        'Threading.Tasks.Sources'

        'Timers'
        'Transactions'
        'Web'
        'Windows.Input'
        'Windows.Markup'
        'Xaml.Permissions'

        'Xml'
        'Xml.Linq'
        'Xml.Resolvers'
        'Xml.Schema'
        'Xml.Serialization'
        'Xml.XPath'
        'Xml.Xsl'
        'Xml.Xsl.Runtime'
    )
    $Names.OmniSharp = @(
        'OmniSharp.Extensions.DebugAdapter.Protocol'
        'OmniSharp.Extensions.DebugAdapter.Protocol.Client'
        'OmniSharp.Extensions.DebugAdapter.Protocol.DebugAdapterConverters'
        'OmniSharp.Extensions.DebugAdapter.Protocol.Events'
        'OmniSharp.Extensions.DebugAdapter.Protocol.Models'
        'OmniSharp.Extensions.DebugAdapter.Protocol.Requests'
        'OmniSharp.Extensions.DebugAdapter.Protocol.Serialization'
        'OmniSharp.Extensions.DebugAdapter.Protocol.Server'
        'OmniSharp.Extensions.DebugAdapter.Server'
        'OmniSharp.Extensions.DebugAdapter.Shared'
        'OmniSharp.Extensions.JsonRpc'
        'OmniSharp.Extensions.JsonRpc.Client'
        'OmniSharp.Extensions.JsonRpc.Generation'
        'OmniSharp.Extensions.JsonRpc.Serialization'
        'OmniSharp.Extensions.JsonRpc.Serialization.Converters'
        'OmniSharp.Extensions.JsonRpc.Server'
        'OmniSharp.Extensions.JsonRpc.Server.Messages'
        'OmniSharp.Extensions.LanguageServer.Client'
        'OmniSharp.Extensions.LanguageServer.Protocol'
        'OmniSharp.Extensions.LanguageServer.Protocol.Client'
        'OmniSharp.Extensions.LanguageServer.Protocol.Client.Capabilities'
        'OmniSharp.Extensions.LanguageServer.Protocol.Client.WorkDone'
        'OmniSharp.Extensions.LanguageServer.Protocol.Document'
        'OmniSharp.Extensions.LanguageServer.Protocol.General'
        'OmniSharp.Extensions.LanguageServer.Protocol.Generation'
        'OmniSharp.Extensions.LanguageServer.Protocol.Models'
        'OmniSharp.Extensions.LanguageServer.Protocol.Progress'
        'OmniSharp.Extensions.LanguageServer.Protocol.Serialization'
        'OmniSharp.Extensions.LanguageServer.Protocol.Serialization.Converters'
        'OmniSharp.Extensions.LanguageServer.Protocol.Server'
        'OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities'
        'OmniSharp.Extensions.LanguageServer.Protocol.Server.WorkDone'
        'OmniSharp.Extensions.LanguageServer.Protocol.Shared'
        'OmniSharp.Extensions.LanguageServer.Protocol.Window'
        'OmniSharp.Extensions.LanguageServer.Protocol.Workspace'
        'OmniSharp.Extensions.LanguageServer.Server'
        'OmniSharp.Extensions.LanguageServer.Server.Abstractions'
        'OmniSharp.Extensions.LanguageServer.Server.Matchers'
        'OmniSharp.Extensions.LanguageServer.Server.Messages'
        'OmniSharp.Extensions.LanguageServer.Server.Pipelines'
        'OmniSharp.Extensions.LanguageServer.Shared'
    )
    $Names.Microsoft = @(
        'Microsoft.ApplicationInsights'
        'Microsoft.ApplicationInsights.Channel'
        'Microsoft.ApplicationInsights.DataContracts'
        'Microsoft.ApplicationInsights.Extensibility'
        'Microsoft.ApplicationInsights.Extensibility.Implementation'
        'Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId'
        'Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints'
        'Microsoft.ApplicationInsights.Extensibility.Implementation.Experimental'
        'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing'
        'Microsoft.ApplicationInsights.Extensibility.W3C'
        'Microsoft.ApplicationInsights.Metrics'
        'Microsoft.ApplicationInsights.Metrics.Extensibility'
        'Microsoft.CodeAnalysis'
        'Microsoft.CodeAnalysis.CSharp'
        'Microsoft.CodeAnalysis.CSharp.Syntax'
        'Microsoft.CodeAnalysis.Diagnostics'
        'Microsoft.CodeAnalysis.Diagnostics.Telemetry'
        'Microsoft.CodeAnalysis.Emit'
        'Microsoft.CodeAnalysis.FlowAnalysis'
        'Microsoft.CodeAnalysis.Operations'
        'Microsoft.CodeAnalysis.Text'
        'Microsoft.CSharp.RuntimeBinder'
        'Microsoft.Extensions.Configuration'
        'Microsoft.Extensions.Configuration.Memory'
        'Microsoft.Extensions.DependencyInjection'
        'Microsoft.Extensions.DependencyInjection.Extensions'
        'Microsoft.Extensions.FileSystemGlobbing'
        'Microsoft.Extensions.FileSystemGlobbing.Abstractions'
        'Microsoft.Extensions.FileSystemGlobbing.Internal'
        'Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments'
        'Microsoft.Extensions.FileSystemGlobbing.Internal.PatternContexts'
        'Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns'
        'Microsoft.Extensions.Logging'
        'Microsoft.Extensions.Logging.Abstractions'
        'Microsoft.Extensions.Options'
        'Microsoft.Extensions.Primitives'
        'Microsoft.Management.Infrastructure'
        'Microsoft.Management.Infrastructure.CimCmdlets'
        'Microsoft.Management.Infrastructure.Generic'
        'Microsoft.Management.Infrastructure.Options'
        'Microsoft.Management.Infrastructure.Serialization'
        'Microsoft.PowerShell'
        'Microsoft.PowerShell.Cim'
        'Microsoft.PowerShell.Cmdletization'
        'Microsoft.PowerShell.Cmdletization.Cim'
        'Microsoft.PowerShell.Cmdletization.Xml'
        'Microsoft.PowerShell.Commands'
        'Microsoft.PowerShell.Commands.GetCounter'
        'Microsoft.PowerShell.Commands.Internal'
        'Microsoft.PowerShell.Commands.Internal.Format'
        'Microsoft.PowerShell.Commands.ShowCommandExtension'
        'Microsoft.PowerShell.Commands.Utility'
        'Microsoft.PowerShell.DesiredStateConfiguration'
        'Microsoft.PowerShell.DesiredStateConfiguration.Internal'
        'Microsoft.PowerShell.EditorServices.Commands'
        'Microsoft.PowerShell.EditorServices.Extensions'
        'Microsoft.PowerShell.EditorServices.Extensions.Services'
        'Microsoft.PowerShell.EditorServices.Hosting'
        'Microsoft.PowerShell.EditorServices.Services.Configuration'
        'Microsoft.PowerShell.EditorServices.Services.DebugAdapter'
        'Microsoft.PowerShell.EditorServices.Services.PowerShell'
        'Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution'
        'Microsoft.PowerShell.EditorServices.Services.PowerShell.Host'
        'Microsoft.PowerShell.EditorServices.Services.TextDocument'
        'Microsoft.PowerShell.EditorServices.Utility'
        'Microsoft.PowerShell.EditorServices.VSCode'
        'Microsoft.PowerShell.EditorServices.VSCode.CustomViews'
        'Microsoft.PowerShell.Internal'
        'Microsoft.PowerShell.MarkdownRender'
        'Microsoft.PowerShell.PSReadLine'
        'Microsoft.PowerShell.Telemetry'
        'Microsoft.Security.Extensions'
        'Microsoft.SqlServer.Server'
        'Microsoft.VisualBasic'
        'Microsoft.VisualBasic.CompilerServices'
        'Microsoft.VisualBasic.FileIO'
        'Microsoft.VisualStudio.Threading'
        'Microsoft.Win32'
        'Microsoft.Win32.SafeHandles'
        'Microsoft.WSMan.Management'

    )

    $Names.All = @(
        $Names.Values | % GetEnumerator  | Sort-Object -unique
    )

    $Selection =
        @( foreach($Name in $GroupName) {
            $Names[ $GroupName ]
        }) | % GetEnumerator | Sort-Object -unique

    if($PassThru) { return $Selection }

    return $Selection | Join-String -f "`nusing namespace {0}"
}
# using namespace System.Collections

Export-ModuleMember -Function @('Dotils.New.UsingStatement')